name: "Smart Voltronic DEV"
version: "1.0.4"
slug: "smart_voltronic_dev"
description: "âš ï¸ Development version â€“ unstable and for testing only"

arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
uart: true

ports:
  1892/tcp: 1892

panel_icon: mdi:solar-power

options:
  # ============================================================
  # âš¡ ONDULEUR 1
  # ============================================================
  inv1_link: "serial"
  inv1_serial_port: "/dev/serial/by-id/CHANGE-ME-1"
  inv1_gateway_host: ""
  inv1_gateway_port: 8899

  # ============================================================
  # âš¡ ONDULEUR 2
  # ============================================================
  inv2_link: "serial"
  inv2_serial_port: "/dev/serial/by-id/CHANGE-ME-2"
  inv2_gateway_host: ""
  inv2_gateway_port: 8899

  # ============================================================
  # âš¡ ONDULEUR 3
  # ============================================================
  inv3_link: "serial"
  inv3_serial_port: "/dev/serial/by-id/CHANGE-ME-3"
  inv3_gateway_host: ""
  inv3_gateway_port: 8899

  # ============================================================
  # ğŸ“¡ MQTT CONFIGURATION
  # ============================================================
  mqtt_section: "â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ MQTT CONFIGURATION â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""

  # ============================================================
  # ğŸ”” OPTIONS
  # ============================================================
  send_bip: true

  # ============================================================
  # ğŸŒ TIMEZONE
  # ============================================================
  timezone_section: "â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ TIMEZONE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
  timezone_mode: "Europe/Paris"
  timezone_custom: "UTC"


schema:
  # Onduleur 1
  inv1_link: list(serial|gateway)
  inv1_serial_port: str?
  inv1_gateway_host: str?
  inv1_gateway_port: int?

  # Onduleur 2
  inv2_link: list(serial|gateway)
  inv2_serial_port: str?
  inv2_gateway_host: str?
  inv2_gateway_port: int?

  # Onduleur 3
  inv3_link: list(serial|gateway)
  inv3_serial_port: str?
  inv3_gateway_host: str?
  inv3_gateway_port: int?

  # SÃ©parateur MQTT
  mqtt_section: str?

  # MQTT
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password

  # Options
  send_bip: bool

  # SÃ©parateur Timezone
  timezone_section: str?

  # Timezone
  timezone_mode: list(Europe/Paris|Europe/Berlin|Europe/Brussels|Europe/Madrid|Europe/Rome|Europe/London|America/New_York|America/Chicago|America/Los_Angeles|America/Montreal|Asia/Dubai|Asia/Tokyo|Australia/Sydney|CUSTOM)
  timezone_custom: str?
