name: "Smart Voltronic Node-RED"
version: "1.0.1"
slug: smart_voltronic
description: "Node-RED Voltronic plug & play: flow mis à jour via MAJ add-on"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false

# (selon ton Supervisor récent)
privileged:
  - SYS_ADMIN

devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2

ports:
  1880/tcp: 1880

webui: "http://[HOST]:[PORT:1880]"
panel_icon: mdi:solar-power

options:
  serial_ports:
    - "/dev/ttyUSB0"
    - "/dev/ttyUSB1"
    - "/dev/ttyUSB2"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""

schema:
  serial_ports:
    - str
    - str?
    - str?
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
