name: "Smart Voltronic DEV"
version: "1.0.2"
slug: "smart_voltronic_dev"
description: "‚ö†Ô∏è Development version ‚Äì unstable and for testing only"

arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
uart: true

ports:
  1892/tcp: 1892

panel_icon: mdi:solar-power

options:
  # =========================
  # ‚ö° ONDULEUR 1
  # =========================
  inv1_link: "serial"           # serial | gateway
  inv1_gateway_host: ""         # ex: 192.168.1.40
  inv1_gateway_port: 8899

  # =========================
  # ‚ö° ONDULEUR 2
  # =========================
  inv2_link: "serial"
  inv2_gateway_host: ""
  inv2_gateway_port: 8899

  # =========================
  # ‚ö° ONDULEUR 3
  # =========================
  inv3_link: "serial"
  inv3_gateway_host: ""
  inv3_gateway_port: 8899

  # =========================
  # üîå PORTS S√âRIE (utilis√©s si invX_link = serial)
  # =========================
  serial_ports:
    - "/dev/serial/by-id/CHANGE-ME-1"
    - "/dev/serial/by-id/CHANGE-ME-2"
    - "/dev/serial/by-id/CHANGE-ME-3"

  # =========================
  # üì° MQTT
  # =========================
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""

  # üîî Option
  send_bip: true

  # =========================
  # üåç Timezone
  # =========================
  timezone_mode: "Europe/Paris"
  timezone_custom: "UTC"

schema:
  # Onduleur 1
  inv1_link: list(serial|gateway)
  inv1_gateway_host: str?
  inv1_gateway_port: int?

  # Onduleur 2
  inv2_link: list(serial|gateway)
  inv2_gateway_host: str?
  inv2_gateway_port: int?

  # Onduleur 3
  inv3_link: list(serial|gateway)
  inv3_gateway_host: str?
  inv3_gateway_port: int?

  # Ports s√©rie
  serial_ports:
    - str
    - str?
    - str?

  # MQTT
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password

  # Option
  send_bip: bool

  # Timezone
  timezone_mode: list(Europe/Paris|Europe/Berlin|Europe/Brussels|Europe/Madrid|Europe/Rome|Europe/London|America/New_York|America/Chicago|America/Los_Angeles|America/Montreal|Asia/Dubai|Asia/Tokyo|Australia/Sydney|CUSTOM)
  timezone_custom: str?
